import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#a44100",
        "surface-bright": "#fcf8ff",
        "presence-violet": "#7C3AED",
        "surface-container-highest": "#e4e1ee",
        "on-error": "#ffffff",
        "on-background": "#1b1b24",
        "on-secondary-container": "#606366",
        "accent-hover": "#4338CA",
        "presence-fuchsia": "#C026D3",
        "surface-container-low": "#f5f2ff",
        "on-tertiary": "#ffffff",
        background: "#fcf8ff",
        outline: "#777587",
        "on-secondary-fixed-variant": "#44474a",
        "surface-dim": "#dcd8e5",
        "presence-orange": "#EA580C",
        "insertion-text": "#16A34A",
        "tertiary-fixed": "#ffdbcc",
        "on-secondary-fixed": "#191c1f",
        "secondary-fixed-dim": "#c4c7ca",
        surface: "#fcf8ff",
        "presence-teal": "#0D9488",
        "surface-container-high": "#eae6f4",
        "document-surface": "#FFFFFF",
        "on-tertiary-fixed-variant": "#7b2f00",
        "text-muted": "#94A3B8",
        "deletion-text": "#DC2626",
        "status-destructive": "#EF4444",
        "inverse-surface": "#302f39",
        "presence-rose": "#E11D48",
        secondary: "#5b5f62",
        "deletion-bg": "#FEF2F2",
        "tertiary-fixed-dim": "#ffb695",
        "on-primary-container": "#dad7ff",
        "on-surface": "#1b1b24",
        error: "#ba1a1a",
        tertiary: "#7e3000",
        "primary-fixed": "#e2dfff",
        "presence-lime": "#65A30D",
        "presence-sky": "#0284C7",
        "text-secondary": "#475569",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "text-primary": "#0F172A",
        "border-subtle": "#E2E8F0",
        "insertion-bg": "#F0FDF4",
        "surface-tint": "#4d44e3",
        "on-primary-fixed-variant": "#3323cc",
        primary: "#3525cd",
        "on-surface-variant": "#464555",
        "surface-container": "#f0ecf9",
        "accent-bg": "#EEF2FF",
        "primary-container": "#4f46e5",
        "border-strong": "#CBD5E1",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e0e2e6",
        "status-warning": "#F59E0B",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f3effc",
        "surface-container-lowest": "#ffffff",
        "app-bg": "#F5F7FA",
        "on-tertiary-fixed": "#351000",
        "primary-fixed-dim": "#c3c0ff",
        "surface-variant": "#e4e1ee",
        "presence-amber": "#D97706",
        "on-primary-fixed": "#0f0069",
        "inverse-primary": "#c3c0ff",
        "panel-surface": "#F9FAFB",
        "secondary-container": "#dee0e4",
        "on-tertiary-container": "#ffd2be",
        "outline-variant": "#c7c4d8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "32px",
        xl: "24px",
        gutter: "16px",
        sm: "8px",
        md: "12px",
        xs: "4px",
        lg: "16px",
        xxl: "32px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "ui-base": ["var(--font-jakarta)", "sans-serif"],
        "ui-xl": ["var(--font-jakarta)", "sans-serif"],
        "ui-xs": ["var(--font-jakarta)", "sans-serif"],
        "ui-sm": ["var(--font-jakarta)", "sans-serif"],
        "ui-lg": ["var(--font-jakarta)", "sans-serif"],
        "display-sm": ["var(--font-jakarta)", "sans-serif"],
        "display-lg": ["var(--font-jakarta)", "sans-serif"],
        h2: ["var(--font-source-serif)", "serif"],
        h1: ["var(--font-source-serif)", "serif"],
        "body-base": ["var(--font-source-serif)", "serif"],
        code: ["var(--font-jetbrains)", "monospace"],
      },
      fontSize: {
        "ui-base": ["15px", { lineHeight: "20px", fontWeight: "400" }],
        "ui-xl": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        h2: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "ui-xs": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "ui-lg": ["17px", { lineHeight: "24px", fontWeight: "500" }],
        "body-base": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "ui-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "display-sm": ["26px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h1: ["26px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["34px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      boxShadow: {
        paper:
          "0px 4px 6px -1px rgba(0, 0, 0, 0.05), 0px 2px 4px -2px rgba(0, 0, 0, 0.05), 0px 10px 15px -3px rgba(0, 0, 0, 0.02)",
        float:
          "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};

export default config;
