"use client";

import * as React from "react";
import { useEditorRef, usePluginOption } from "platejs/react";

import { discussionPlugin } from "@/components/editor/plugins/discussion-kit";
import {
  getDiscussions,
  saveDiscussions,
  createComment,
  updateComment,
  deleteComment,
  resolveComment,
  bodyFromRich,
  type DiscussionUser,
  type TDiscussion,
} from "@/lib/api/comments";
import * as auth from "@/lib/api/auth";
import * as assignments from "@/lib/api/assignments";

const avatar = (seed: string) =>
  `https://api.dicebear.com/9.x/glass/svg?seed=${seed}`;

// Backend comment ids are UUIDs. Anything else (e.g. a suggestion-thread id
// generated by a plugin we don't control) is kept client-side only.
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Bridges the discussion plugin's in-memory option store to the backend
 * comments API. Comment ids are client-generated UUIDs shared with the
 * backend (POST sends the id), so the comment marks anchored in the Yjs text,
 * the plugin state, and the backend rows all agree — across reloads and
 * across users.
 *
 * Watches the `discussions` option and write-through persists every change:
 *   - new comments        → POST   /documents/{id}/comments (idempotent by id)
 *   - edited bodies       → PATCH  /comments/{id}
 *   - removed comments    → DELETE /comments/{id}
 *   - resolve/reopen      → PATCH  /comments/{id}/resolve
 *
 * Rendered inside <Plate> so it can use the editor option hooks.
 */
export function DiscussionSync({ docId }: { docId: string }) {
  const editor = useEditorRef();
  const hydratedRef = React.useRef(false);
  // body text last persisted to the backend, per comment id. Doubles as the
  // "already synced" set (key present = persisted).
  const syncedBodyRef = React.useRef<Map<string, string>>(new Map());
  // Last-known resolved state per thread, to detect resolve/unresolve toggles.
  const resolvedRef = React.useRef<Map<string, boolean>>(new Map());
  const discussions = usePluginOption(
    discussionPlugin,
    "discussions",
  ) as TDiscussion[];

  // Hydrate this document's threads + wire the signed-in user as author.
  React.useEffect(() => {
    let cancelled = false;
    hydratedRef.current = false;
    syncedBodyRef.current = new Map();
    resolvedRef.current = new Map();

    (async () => {
      // Build the user map so EVERY comment author resolves to a name/avatar:
      // start from the org roster, then layer the signed-in user on top.
      const usersMap: Record<string, DiscussionUser> = {
        ...(editor.getOption(discussionPlugin, "users") as Record<
          string,
          DiscussionUser
        >),
      };
      try {
        const roster = await assignments.listOrgUsers();
        for (const u of roster) {
          usersMap[u.id] = {
            id: u.id,
            name: u.display_name,
            avatarUrl: avatar(u.id),
          };
        }
      } catch {
        /* backend unreachable — fall back to just the current user below */
      }
      if (cancelled) return;

      const me = auth.getCurrentUser();
      if (me) {
        usersMap[me.id] = { id: me.id, name: me.name, avatarUrl: avatar(me.id) };
        editor.setOption(discussionPlugin, "currentUserId", me.id);
      }
      editor.setOption(discussionPlugin, "users", usersMap);

      const loaded = await getDiscussions(docId);
      if (cancelled) return;
      // Everything loaded from the backend is already persisted.
      for (const d of loaded) {
        resolvedRef.current.set(d.id, d.isResolved);
        for (const c of d.comments)
          syncedBodyRef.current.set(c.id, bodyFromRich(c.contentRich));
      }
      editor.setOption(discussionPlugin, "discussions", loaded);
      // Mark hydrated only after the initial load is applied, so the persist
      // effect below never clobbers stored threads with the seed value.
      hydratedRef.current = true;
    })();

    return () => {
      cancelled = true;
    };
  }, [docId, editor]);

  // Persist changes once hydration has completed: cache locally, then
  // write-through to the backend. Every call is best-effort — a failure keeps
  // the previous synced state so the next change retries it.
  React.useEffect(() => {
    if (!hydratedRef.current) return;
    void saveDiscussions(docId, discussions);

    const presentIds = new Set<string>();

    for (const d of discussions) {
      for (const c of d.comments) {
        presentIds.add(c.id);
        if (!UUID_RE.test(c.id)) continue; // client-only thread (e.g. suggestions)
        const body = bodyFromRich(c.contentRich);
        if (!body) continue;

        const synced = syncedBodyRef.current.get(c.id);
        if (synced === undefined) {
          // New comment → POST under the client id. The root comment's id
          // equals the discussion id; replies point at it as their parent.
          syncedBodyRef.current.set(c.id, body); // optimistic: no double-POST
          const isReply = c.id !== d.id;
          void createComment(docId, body, {
            id: c.id,
            parentCommentId:
              isReply && UUID_RE.test(d.id) ? d.id : undefined,
            anchor:
              !isReply && d.documentContent
                ? { documentContent: d.documentContent }
                : undefined,
          }).catch(() => {
            syncedBodyRef.current.delete(c.id); // allow a retry on next change
          });
        } else if (synced !== body) {
          // Edited comment → PATCH.
          syncedBodyRef.current.set(c.id, body);
          void updateComment(c.id, body).catch(() => {
            syncedBodyRef.current.set(c.id, synced); // retry on next change
          });
        }
      }

      // Resolve / unresolve toggles on known threads → PATCH.
      const prev = resolvedRef.current.get(d.id);
      if (prev !== undefined && prev !== d.isResolved) {
        resolvedRef.current.set(d.id, d.isResolved);
        if (UUID_RE.test(d.id))
          void resolveComment(d.id, d.isResolved).catch(() => {});
      } else if (prev === undefined) {
        resolvedRef.current.set(d.id, d.isResolved);
      }
    }

    // Comments that were synced before but are gone from the plugin state were
    // deleted by the user → DELETE on the backend too.
    for (const [id] of syncedBodyRef.current) {
      if (presentIds.has(id)) continue;
      syncedBodyRef.current.delete(id);
      resolvedRef.current.delete(id);
      if (UUID_RE.test(id)) void deleteComment(id).catch(() => {});
    }
  }, [discussions, docId]);

  return null;
}
