"use client";

import * as React from "react";
import { useEditorRef, usePluginOption } from "platejs/react";

import { discussionPlugin } from "@/components/editor/plugins/discussion-kit";
import {
  getDiscussions,
  saveDiscussions,
  createComment,
  updateComment,
  deleteComment,
  resolveComment,
  bodyFromRich,
  type DiscussionUser,
  type TDiscussion,
} from "@/lib/api/comments";
import * as auth from "@/lib/api/auth";
import * as assignments from "@/lib/api/assignments";
import { useDocument } from "@/lib/store/document-store";

const avatar = (seed: string) =>
  `https://api.dicebear.com/9.x/glass/svg?seed=${seed}`;

// Backend comment ids are UUIDs. Anything else (e.g. a suggestion-thread id
// generated by a plugin we don't control) is kept client-side only.
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const POLL_INTERVAL_MS = 5000;

/**
 * Merge a fresh backend read with the current in-memory state so a poll never
 * wipes out a comment/reply that's still mid-flight (POST initiated but not
 * yet reflected in the backend's response yet).
 *
 * `neverSynced` distinguishes the two reasons a local item can be missing
 * from `backend`: never seen as synced before (still uploading — KEEP it) vs.
 * previously confirmed but now absent (deleted, by this client or another —
 * DROP it, otherwise a poll would resurrect anything another user deletes).
 */
function mergeWithPending(
  backend: TDiscussion[],
  current: TDiscussion[],
  neverSynced: (id: string) => boolean,
): TDiscussion[] {
  const backendIds = new Set(backend.map((d) => d.id));
  const pendingDiscussions = current.filter(
    (d) => !backendIds.has(d.id) && neverSynced(d.id),
  );
  const merged = backend.map((bd) => {
    const local = current.find((cd) => cd.id === bd.id);
    if (!local) return bd;
    const backendCommentIds = new Set(bd.comments.map((c) => c.id));
    const pendingComments = local.comments.filter(
      (c) => !backendCommentIds.has(c.id) && neverSynced(c.id),
    );
    return pendingComments.length ? { ...bd, comments: [...bd.comments, ...pendingComments] } : bd;
  });
  return [...merged, ...pendingDiscussions];
}

/**
 * Bridges the discussion plugin's in-memory option store to the backend
 * comments API. Comment ids are client-generated UUIDs shared with the
 * backend (POST sends the id), so the comment marks anchored in the Yjs text,
 * the plugin state, and the backend rows all agree — across reloads and
 * across users.
 *
 * Watches the `discussions` option and write-through persists every change:
 *   - new comments        → POST   /documents/{id}/comments (idempotent by id)
 *   - edited bodies       → PATCH  /comments/{id}
 *   - removed comments    → DELETE /comments/{id}
 *   - resolve/reopen      → PATCH  /comments/{id}/resolve
 *
 * Rendered inside <Plate> so it can use the editor option hooks.
 */
export function DiscussionSync({ docId }: { docId: string }) {
  const editor = useEditorRef();
  const { commentsOpen } = useDocument();
  const hydratedRef = React.useRef(false);
  // body text last persisted to the backend, per comment id. Doubles as the
  // "already synced" set (key present = persisted).
  const syncedBodyRef = React.useRef<Map<string, string>>(new Map());
  // Last-known resolved state per thread, to detect resolve/unresolve toggles.
  const resolvedRef = React.useRef<Map<string, boolean>>(new Map());
  const discussions = usePluginOption(
    discussionPlugin,
    "discussions",
  ) as TDiscussion[];
  // Latest discussions in a ref so the poll effect (below) can read current
  // state without re-registering its interval on every keystroke.
  const discussionsRef = React.useRef(discussions);
  React.useEffect(() => {
    discussionsRef.current = discussions;
  }, [discussions]);

  // Hydrate this document's threads + wire the signed-in user as author.
  React.useEffect(() => {
    let cancelled = false;
    hydratedRef.current = false;
    syncedBodyRef.current = new Map();
    resolvedRef.current = new Map();

    (async () => {
      // Build the user map so EVERY comment author resolves to a name/avatar:
      // start from the org roster, then layer the signed-in user on top.
      const usersMap: Record<string, DiscussionUser> = {
        ...(editor.getOption(discussionPlugin, "users") as Record<
          string,
          DiscussionUser
        >),
      };
      try {
        const roster = await assignments.listOrgUsers();
        for (const u of roster) {
          usersMap[u.id] = {
            id: u.id,
            name: u.display_name,
            avatarUrl: avatar(u.id),
          };
        }
      } catch {
        /* backend unreachable — fall back to just the current user below */
      }
      if (cancelled) return;

      const me = auth.getCurrentUser();
      if (me) {
        usersMap[me.id] = { id: me.id, name: me.name, avatarUrl: avatar(me.id) };
        editor.setOption(discussionPlugin, "currentUserId", me.id);
      }
      editor.setOption(discussionPlugin, "users", usersMap);

      const loaded = await getDiscussions(docId);
      if (cancelled) return;
      // Everything loaded from the backend is already persisted.
      for (const d of loaded) {
        resolvedRef.current.set(d.id, d.isResolved);
        for (const c of d.comments)
          syncedBodyRef.current.set(c.id, bodyFromRich(c.contentRich));
      }
      editor.setOption(discussionPlugin, "discussions", loaded);
      // Mark hydrated only after the initial load is applied, so the persist
      // effect below never clobbers stored threads with the seed value.
      hydratedRef.current = true;
    })();

    return () => {
      cancelled = true;
    };
  }, [docId, editor]);

  // Pick up OTHER users' comments/resolves/edits while the panel is open —
  // comments are REST-backed (not part of the Yjs doc), so without this a
  // collaborator's new comment or resolve never appears until this client
  // reloads. Merged (not replaced) so an in-flight local write can't be
  // wiped out by a poll landing mid-request.
  React.useEffect(() => {
    if (!commentsOpen) return;
    const interval = setInterval(() => {
      if (!hydratedRef.current) return;
      void getDiscussions(docId).then((backend) => {
        // Snapshot "was this ever confirmed synced" BEFORE updating tracking
        // below, so the merge can tell "still uploading" (never synced) apart
        // from "deleted elsewhere" (was synced, now missing from backend).
        const neverSynced = (id: string) =>
          !syncedBodyRef.current.has(id) && !resolvedRef.current.has(id);
        const merged = mergeWithPending(backend, discussionsRef.current, neverSynced);

        // Re-sync tracking to the backend's authoritative state for every
        // CONFIRMED item (covers edits/resolves made by other users).
        for (const d of backend) {
          resolvedRef.current.set(d.id, d.isResolved);
          for (const c of d.comments) {
            syncedBodyRef.current.set(c.id, bodyFromRich(c.contentRich));
          }
        }
        editor.setOption(discussionPlugin, "discussions", merged);
      });
    }, POLL_INTERVAL_MS);
    return () => clearInterval(interval);
  }, [commentsOpen, docId, editor]);

  // Persist changes once hydration has completed: cache locally, then
  // write-through to the backend. Every call is best-effort — a failure keeps
  // the previous synced state so the next change retries it.
  React.useEffect(() => {
    if (!hydratedRef.current) return;
    void saveDiscussions(docId, discussions);

    const presentIds = new Set<string>();

    for (const d of discussions) {
      for (const c of d.comments) {
        presentIds.add(c.id);
        if (!UUID_RE.test(c.id)) continue; // client-only thread (e.g. suggestions)
        const body = bodyFromRich(c.contentRich);
        if (!body) continue;

        const synced = syncedBodyRef.current.get(c.id);
        if (synced === undefined) {
          // New comment → POST under the client id. The root comment's id
          // equals the discussion id; replies point at it as their parent.
          syncedBodyRef.current.set(c.id, body); // optimistic: no double-POST
          const isReply = c.id !== d.id;
          void createComment(docId, body, {
            id: c.id,
            parentCommentId:
              isReply && UUID_RE.test(d.id) ? d.id : undefined,
            anchor:
              !isReply && d.documentContent
                ? { documentContent: d.documentContent }
                : undefined,
          }).catch(() => {
            syncedBodyRef.current.delete(c.id); // allow a retry on next change
          });
        } else if (synced !== body) {
          // Edited comment → PATCH.
          syncedBodyRef.current.set(c.id, body);
          void updateComment(c.id, body).catch(() => {
            syncedBodyRef.current.set(c.id, synced); // retry on next change
          });
        }
      }

      // Resolve / unresolve toggles on known threads → PATCH.
      const prev = resolvedRef.current.get(d.id);
      if (prev !== undefined && prev !== d.isResolved) {
        resolvedRef.current.set(d.id, d.isResolved);
        if (UUID_RE.test(d.id))
          void resolveComment(d.id, d.isResolved).catch(() => {});
      } else if (prev === undefined) {
        resolvedRef.current.set(d.id, d.isResolved);
      }
    }

    // Comments that were synced before but are gone from the plugin state were
    // deleted by the user → DELETE on the backend too.
    for (const [id] of syncedBodyRef.current) {
      if (presentIds.has(id)) continue;
      syncedBodyRef.current.delete(id);
      resolvedRef.current.delete(id);
      if (UUID_RE.test(id)) void deleteComment(id).catch(() => {});
    }
  }, [discussions, docId]);

  return null;
}
