# =============================================================================
# app/api/internal.py  —  /api/internal/*  (service-to-service, NOT user-facing)
#
# The ai-gateway reports token usage here after each vendor call. Two-layer
# trust:
#   1. AUTHN — the caller must present a valid SERVICE JWT (typ="service", signed
#      with the shared AI_GATEWAY_SECRET) in the Authorization header, proving it
#      is the gateway.
#   2. SCOPE — the reported usage is attributed using the ORIGINAL AI grant the
#      gateway forwards, from which org/document/user/vendor/model are derived.
#      The gateway cannot fabricate who/what the usage belongs to.
#
# `request_id` (one per upstream call, generated by the gateway) makes the insert
# idempotent, so a retry can never double-count.
# =============================================================================

import jwt
from fastapi import APIRouter, Depends, Header, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.models.database_models import AiUsageEvent
from app.schemas.ai import AIUsageReportRequest, AIUsageReportResponse
from app.services.ai_grant_service import verify_service_token, verify_grant

router = APIRouter()


async def require_service_token(authorization: str = Header(default="")) -> dict:
    """Validate the gateway's service JWT from the Authorization: Bearer header."""
    if not authorization.lower().startswith("bearer "):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Missing service token")
    token = authorization.split(" ", 1)[1].strip()
    try:
        return verify_service_token(token)
    except jwt.PyJWTError as e:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail=f"Invalid service token: {e}")


@router.post("/ai/usage", response_model=AIUsageReportResponse)
async def report_ai_usage(
    data: AIUsageReportRequest,
    db: AsyncSession = Depends(get_db),
    _service: dict = Depends(require_service_token),
):
    # Scope comes from the grant, not from the (trusted) gateway's word.
    try:
        grant = verify_grant(data.grant)
    except jwt.PyJWTError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Invalid grant: {e}")

    # Idempotency: a repeated request_id is a no-op.
    existing = (
        await db.execute(select(AiUsageEvent).where(AiUsageEvent.request_id == data.request_id))
    ).scalars().first()
    if existing is not None:
        return AIUsageReportResponse(recorded=False, request_id=data.request_id)

    input_tokens = max(0, int(data.input_tokens or 0))
    output_tokens = max(0, int(data.output_tokens or 0))
    db.add(AiUsageEvent(
        org_id=grant["org"],
        document_id=grant.get("doc"),
        user_id=grant.get("sub"),
        vendor=grant.get("vendor", "unknown"),
        model_key=grant.get("model", "unknown"),
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        total_tokens=input_tokens + output_tokens,
        request_id=data.request_id,
    ))
    await db.commit()
    return AIUsageReportResponse(recorded=True, request_id=data.request_id)
